DESC superhero;

DELETE FROM SUPERHEROES;

-- Create a table by other table, disregarding values.
CREATE TABLE SUPERHEROES_BKP AS SELECT * FROM SUPERHEROES WHERE 1=2;

-- Trigger to Clone/Backup a table to other.
CREATE OR REPLACE TRIGGER sh_bkp
BEFORE INSERT OR DELETE OR UPDATE ON SUPERHEROES
FOR EACH ROW
ENABLE
BEGIN
    IF inserting THEN
        INSERT INTO SUPERHEROES_BKP (SH_NAME) VALUES (:NEW.SH_NAME);
    ELSIF deleting THEN
        DELETE FROM SUPERHEROES_BKP WHERE SH_NAME = :OLD.SH_NAME;
    ELSIF updating THEN
        UPDATE SUPERHEROES_BKP SET SH_NAME = :NEW.SH_NAME WHERE SH_NAME = :OLD.SH_NAME;
    end if;
end;

INSERT ALL
	INTO SUPERHEROES(SH_NAME) VALUES ('Superman')
	INTO SUPERHEROES(SH_NAME) VALUES ('Batman')
	INTO SUPERHEROES(SH_NAME) VALUES ('Ironman')
	INTO SUPERHEROES(SH_NAME) VALUES ('Spiderman')
SELECT 1 FROM DUAL;
SELECT * FROM SUPERHEROES;
SELECT * FROM SUPERHEROES_BKP;

UPDATE SUPERHEROES SET SH_NAME = 'ERIC' WHERE SH_NAME = 'Superman';
SELECT * FROM SUPERHEROES;
SELECT * FROM SUPERHEROES_BKP;

DELETE FROM SUPERHEROES WHERE SH_NAME = 'ERIC';
SELECT * FROM SUPERHEROES;
SELECT * FROM SUPERHEROES_BKP;


